### ISSUE TITLE
Collection Export: Issue while processing ["All"]

### ISSUE THREAD

**Issue by vikassinghrajput** [ComPlat/chemotion_ELN#555] opened 2021-10-17 17:29 UTC
- [ ] I am an ELNer
- [ ] I am a developer
- [x] I am a system/ELN admin

# Expected Behavior

Export collection should create a zip file.

# Current Behavior

It's giving failure message when using 'All' under export collections.

# Failure Information 

Collection Export: There was an issue while processing ["All"]

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click on 'Export collections'
2. Choose 'All'
3. It will give an error

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - OS: [e.g. iOS] Linux Mint
 - [x] Chrome Browser 
 - [ ] Firefox Browser
 - ELN version, or branch, or commit : 0.9.1

## Failure Logs / Screenshots

Include any relevant log snippets or files here.
![Export_all_failure](https://user-images.githubusercontent.com/48114739/137638270-b0bb2f5a-116c-4eb4-97c1-c5e6c0ab2a8a.png)

**Comment by TasnimMehzabin** [comment] 2023-10-20 11:24
I have tried to reproduce this issue in the [uncharted](https://uncharted.chemotion.ibcs.kit.edu/) instance. This issue seems to be resolved by now. I have added some screenshots here for the reference purpose. I am closing this issue for now. We can open this again in the future if we get to reproduce the issue.

![uncharted_1](https://github.com/ComPlat/chemotion_ELN/assets/8912580/7fdcad93-ad76-454f-88b0-31c498cadf4a)
![uncharted_2](https://github.com/ComPlat/chemotion_ELN/assets/8912580/4d5a3191-52b0-4be5-a21b-1e10ce546f18)
![complat_1](https://github.com/ComPlat/chemotion_ELN/assets/8912580/7c838709-99fb-48e6-8767-b1b6bd3820db)

**Closed by TasnimMehzabin** 2023-10-20 11:24 UTC
Labels: bug
