### ISSUE TITLE
Inbox size

### ISSUE THREAD

**Issue by SimoneGraessle** [ComPlat/chemotion_ELN#1606] opened 2023-10-31 07:13 UTC
The inbox size is not very optimal. 
When you open the inbox, it's so big that you can't see any reactions. 
That's why you always have to move the inbox back and forth to find the reaction you want to move the analytics to. To add the analytics you have to move the inbox back to the other side. 
That is why it would be good if the inbox does not open as a separate window. It should only open downwards, as it did before. 

The file is also not deleted from the inbox when you assign it to a sample.

**Comment by TasnimMehzabin** [comment] 2023-11-07 15:16
@SimoneGraessle We were not able to reproduce the following issue in uncharted instance or the production instance.

> The file is also not deleted from the inbox when you assign it to a sample. 

Could you kindly check again if you are getting the issue and if yes, on which instance?

Thank you so much for your valuable feedback.

**Comment by SimoneGraessle** [comment] 2023-11-14 09:43
I have checked it again. As soon as you reload the page, the files are deleted from the inbox. 
In the past, it was deleted immediately after moving it to an analysis.

**Comment by SimoneGraessle** [comment] 2023-11-17 06:31
I have a question: Why is the inbox now only at the top of the bar?
It's still the same problem now. If you open the inbox from the top now, it is as big again and covers the complete left side of the ELN. 
The Inbox should already be located on the left side under the Synchronized-Collection. 
But should only open downwards and not as a separate "tab".

**Comment by PiTrem** [comment] 2023-11-17 07:08
Hello @SimoneGraessle 

> I have checked it again. As soon as you reload the page, the files are deleted from the inbox. In the past, it was deleted immediately after moving it to an analysis.

this should be resolved with https://github.com/ComPlat/chemotion_ELN/pull/1446/files

> I have a question: Why is the inbox now only at the top of the bar?

While doing the same, the floating inbox has more functions than the Inbox-directory in the collection panel.
To avoid duplicating the feature and to simplify the UI, but also based on others' feedback, only the floating Inbox was kept.

The current Inbox dimensions can indeed be at time problematic and we will  be sorting this out asap.

**Closed** 2023-12-12 06:58 UTC
Labels: discussion, urgent
