### ISSUE TITLE
info on how to send data to ELN per email

### ISSUE THREAD

**Issue by nicolejung** [ComPlat/chemotion_ELN#1514] opened 2023-09-04 06:32 UTC
A feature that only a few people know is that one can send data to the ELN inbox per email. Please ensure that if this is configured, the people using the ELN instance know the email address they have to send their data to. 
Please ensure that for chemotion ELN - complat instance, the email address is given at the landing page https://complat-eln.ioc.kit.edu/home

**Comment by endevor-music** [comment] 2023-09-05 06:35
If it is not already, this should also be included in the ELN documentation, so users (& developers, like myself!)  know that it is a feature that exists.

**Comment by endevor-music** [comment] 2023-09-15 13:11
Hi @nicolejung - is this issue a duplicate of https://github.com/ComPlat/chemotion_ELN/issues/1500?

**Comment by PiTrem** [comment] 2023-09-15 13:30
if the mail collector is configured (configuration exists, eg: https://github.com/ComPlat/chemotion_ELN/blob/main/lib/datacollector/mailcollector.rb#L9) then the configured email address can be sent to the client over the ui_api (https://github.com/ComPlat/chemotion_ELN/blob/main/app/api/chemotion/ui_api.rb#L18) and displayed with an explanation through an Info btn in the inbox.

![image](https://github.com/ComPlat/chemotion_ELN/assets/15799181/151beb6a-9e1a-453b-942a-191de968e1e8)

**Comment by TasnimMehzabin** [comment] 2023-10-20 08:20
Related information are in the documentation - https://www.chemotion.net/docs/eln/devices#mail-collector
Maybe we can think about adding additional information, if required, along with showing the address in the UI.

**Comment by adambasha0** [comment] 2023-10-30 15:19
@nicolejung @PiTrem 
kindly let me know if you need to adjust info message accordingly 
![image](https://github.com/ComPlat/chemotion_ELN/assets/55552142/5079a738-a8fd-44cc-a21f-d50d8020e3e4)

**Comment by nicolejung** [comment] 2023-10-31 15:32
I think the text in the information button is ok -> but it seems to me that it is hard to find this information... I have the feeling we need an additional place for this information. Perhaps we can think of other, additional solutions for a next version.

**Closed** 2023-11-16 05:40 UTC
