### ISSUE TITLE
Open NMRium wrapper from ELN

### ISSUE THREAD

**Issue by baolanlequang** [ComPlat/chemotion_ELN#964] opened 2022-10-13 11:57 UTC
- I am a developer

# Description
1. User can view NMR spectra data in NMRium from Chemotion ELN

**Comment by FabianMauz** [comment] 2023-02-07 08:52
seems to be duplicate of

https://github.com/ComPlat/chemotion_ELN/issues/439

can somebody confirm this?

**Comment by baolanlequang** [comment] 2023-02-07 08:59
@FabianMauz Yes, it is a duplicate.

**Comment by FabianMauz** [comment] 2023-02-07 09:02
@baolanlequang  Thank you, i will close the other on to avoid confusion.

**Closed** 2023-03-02 23:50 UTC
Labels: feature
