### ISSUE TITLE
solid phase synthesis: resin "ball" not visible in preview and reaction details

### ISSUE THREAD

**Issue by SylviaVanderheiden** [ComPlat/chemotion_ELN#1586] opened 2023-10-20 13:13 UTC
- I am an ELNer

# Expected Behavior

Resins (polymeric structure) are beeing displayed by some kind of ball which is available in the editor. Worked well in the past.

# Current Behavior
The Ball representing a resin in ELN is not visible in the preview of a reaction (hovering over the reaction numbers) or in the details of a reaction

# Failure Information 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

discussed with Paggy and Claire already

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

 - Chrome Browser 
 ELN version 1.7.2

## Failure Logs / Screenshots

Include any relevant log snippets or files here.
![resin_not visible_02](https://github.com/ComPlat/chemotion_ELN/assets/94039752/9f4e397a-a6b3-4399-a539-c0175caae60e)

![resin_not visible_01](https://github.com/ComPlat/chemotion_ELN/assets/94039752/3953fbeb-eecb-4e95-92cd-21ef9f090239)

**Comment by phuang26** [comment] 2023-10-23 07:43
[video](https://drive.google.com/file/d/1NWX6QjYxRoBQH0zZfNFMr7giJRCytQFz/view?usp=share_link)

Version: 1.8.0
Base revision: c4200dffa

not working at ELN 1.8 as well (c4200dffa)

**Comment by adambasha0** [comment] 2023-10-24 08:33
I could not reproduce this error in current version. @PiTrem, shall we close it?

**Closed** 2023-11-06 16:36 UTC
Labels: bug
