### ISSUE TITLE
Sample list is empty after (full page) reload.

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#411] opened 2021-05-12 14:43 UTC
- [ ] I am an ELNer
- [x] I am a developer
- [x] I am a system/ELN admin

# Expected Behavior

I'd say the list should be filled with entries.

# Current Behavior

List is empty

# Failure Information 

As seen in the gif.

## Steps to Reproduce

See the GIF, Note that this happens randomly in like 1 out of 5 cases.

## Context

 - OS: Linux
 - [x] Chrome Browser 
 - [ ] Firefox Browser
 - ELN version: v.0.8.0

## Failure Logs / Screenshots
![no list](https://user-images.githubusercontent.com/209056/117994308-bb80ee80-b340-11eb-99c1-f22263615cb7.gif)

**Comment by adambasha0** [comment] 2023-10-24 08:35
I could not reproduce this error in current version 1.8, neith on complat. @PiTrem shall we close it?

**Comment by TasnimMehzabin** [comment] 2023-10-26 08:54
@adambasha0 @PiTrem I was able to reproduce the issue in the uncharted instance however not in the complat one. I have added two screencasts here for reference purpose.


[uncharted.webm](https://github.com/ComPlat/chemotion_ELN/assets/8912580/5f511368-ec19-4a97-927f-a7252f0e55ab)
[complat_instance.webm](https://github.com/ComPlat/chemotion_ELN/assets/8912580/9e7c90a2-81a0-461d-89d8-6fc38ddb25cc)

**Comment by PiTrem** [comment] 2023-10-26 11:06
It appears that there is an intermittent problem when rapidly reloading the page after clicking on a collection. 

In some instances, the query to fetch the list of elements (here samples) inside the current collection is not being executed, and the list is not displayed as expected.
 
Note that there is no error logged; the code on the page is not in a inoperative condition and getting the list can triggered by further actions.  The issue could stem from an inconsistent state.

We have been investigating this issue, and it seems that with our latest version, it has become less reproducible, which is a positive sign. This might indicate that we have made some improvements in handling these rapid actions, but we are not certain the issue for such a, probably infrequent, scenario (reloading in the middle of an action ) can be fully resolved currently. 

Will close for now.

**Closed by PiTrem** 2023-10-26 11:06 UTC
Labels: bug, confirmed
