### ISSUE TITLE
Inbox font is serif

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#573] opened 2021-11-15 12:02 UTC
See the following picture:
![image](https://user-images.githubusercontent.com/209056/141778453-c7bf6eb7-2e80-424f-b0e0-50abc0d15efa.png)

Font for inbox is set to serif as it is embedded in the `<i>` tag used to render the icon (wtf?). In addition, someone thought it's a good idea to use spaces to create spacing between icon and text (wtf? wtf?). I suggest: move the text outside the `<i>` tag and use proper CSS to create a margin (see [margin](https://developer.mozilla.org/de/docs/Web/CSS/margin)).

**Comment by NRayya** [comment] 2021-11-18 08:30
Good morning Peter
The font issue has already been fixed and it is waiting for review. This issue is a duplicate of the issue [#498 ](https://github.com/ComPlat/chemotion_ELN/issues/498)

**Comment by ptrxyz** [comment] 2021-11-18 10:21
Yay :)
thanks!

**Closed** 2021-12-08 19:30 UTC
Labels: bug, duplicate, confirmed
