### ISSUE TITLE
After Upgrade to latest Chemotion ELN Version the information on the actually installed Version is wrong or Update didn't work as expected

### ISSUE THREAD

**Issue by MichaelOCI** [ComPlat/chemotion_ELN#1243] opened 2023-03-27 09:49 UTC
- I am a system/ELN admin

# Expected Behavior

The installed Chemotion Version after Upgrade should be clear.

# Current Behavior

After updating Chemotion ELN the current version the page about Chemotion shows version 1.4.1. The Changelog includes Version 1.5.0 and according to the docker-compose.yml the installed image should be 1.5.0 
If 1.5.0 was installed the beaviour is confusing. If 1.4.1 was installed instead the upgrade went wrong.

## Steps to Reproduce

1. sudo docker compose down --remove-orphans
2. replace docker-compose.yml
3. docker volume rm chemotion_app
4. edit configuration
5. docker compose up

## Context

Occured on two test setups. Both Ubuntu. One with Chemotion ELN 1.4.1 installed, one with Chemotion ELN 1.3.0 installed.

**Comment by PiTrem** [comment] 2023-04-26 06:05
something went wrong with uploading the  images.
I can confirm that the [images for  1.5.3 ](https://hub.docker.com/r/ptrxyz/chemotion/tags) now contains the ELN 1.5.3
(which was not the case  yesterday morning).
Sorry for the mishap

**Comment by harivyasi** [comment] 2023-04-26 13:49
@MichaelOCI, given the mistake described above, one needs to re-download the new images from DockerHub. To do so, you can remove the existing images (by executing `docker compose down --remove-orphans` followed by `docker rmi $(docker compose images -q)`; this removes images associated with a particular `docker-compose,yml` file). Then following the steps 3 to 5 above should work as intended.

Please consider closing the issue if this solves the problem.

**Closed** 2023-04-27 10:07 UTC
Labels: bug
